config/routes.rb
Rails.application.routes.draw do

resources :songs 
root :to => redirect('/songs')

  get '/songs' => 'songs#index' 
  get '/songs/new' => 'songs#new' 
  get '/songs/edit' => 'songs#edit' 
  post '/songs/new' => 'songs#create' 
  put '/songs/:id/edit' => 'songs#update'
end

app/models/song.rb
class Song < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController 
	def index  
		@songs = Song.all 
  	end 
  	
  	def show
  		id = params[:id] # retrieve movie ID from URI route
  		@song = Song.find(id) # look up movie by unique ID
	end 

	def new
	  # default: render 'new' template
	end 

	def create 
		@song = Song.create!(songs_params) 
		redirect_to songs_path 
	end   

	def edit 
	    @song = Song.find(params[:id]) 
	end 

	def update 
	    @song = Song.find(params[:id]) 
	    if @song.update_attributes(songs_params) 
	      redirect_to(:action => 'index', :id => @song.id) 
	    else 
           render 'edit' 
	     end 
	 end 

	def destroy
        @song = Song.find(params[:id])
        @song.destroy
        redirect_to(:action => 'index')
    end
	
	private
	def songs_params 
		params.require(:song).permit(:title, :singer, :writer, :release_date, :genere, :length)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Songs !!! 
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
 
  %body
    #main
      = yield

app/views/songs/edit.html.haml
.song
  .container
    = form_for(@song) do |f|
      .field
        = f.label :song
        %br/
        = f.text_field :singer
        %br/
        = f.text_field :writer
        %br/
        = f.date_field :release_date
        %br/
        = f.text_field :genere
        %br/
        = f.text_field :length
        %br/
        = f.text_field :title
        %br/
      .actions
        = f.submit "Update"

app/views/songs/index.html.haml
%h1 All Songs
 
%table#songs
  %thead
    %tr
      %th Title
      %th Singer
      %th Writer 
      %th Release Date
      %th Genere
      %th Length  
      %th Edit 
      %th Delete 
  %tbody
    - @songs.each do |song|
      %tr
        %td= song.title
        %td= song.singer 
        %td= song.writer 
        %td= song.release_date
        %td= song.genere
        %td= song.length  
        %td= link_to 'Edit', :action => 'edit' ,:id => song.id 
        %td= link_to 'Delete', song_path(song), :method => :delete 
  = link_to 'Add new song', '/songs/new'

app/views/songs/new.html.haml
%h2 Create New Song
 
= form_tag songs_path, :method => :post do
 
  = label :song, :title, 'Title'
  = text_field :song, :title 

  = label :song, :singer, 'Singer'
  = text_field :song, :singer 

  = label :song, :writer, 'Writer'
  = text_field :song, :writer  
 
  = label :song, :release_date, 'Release date'
  = text_field :song, :release_date 

  = label :song, :genere, 'Genere'
  = text_field :song, :genere 

  = label :song, :length, 'Lenght'
  = text_field :song, :length

 
  = submit_tag 'Save Changes'

app/views/songs/show.html.haml
%h2 Details about #{@song.title}
 
%ul#details
  %li
    Title:
    = @song.title
  %li
    Released on:
    = @song.release_date.strftime("%B %d, %Y")
 
%h3 Genere:
 
%p#genere = @song.genere
 
= link_to 'Back to song list', songs_path